version: '3'

services:
  # Reverse proxy for all dockerized servies exposed to the web
  proxy:
    build: ./proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-conf.d:/etc/nginx/conf.d
      - proxy-vhost.d:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-dhparam:/etc/nginx/dhparam
    networks:
      proxy-tier:
        # specify a static IP address so that backend services can set this address as a trusted proxy
        ipv4_address: <SPECIFY-IP-HERE>

  # Automatic Nginx setup as a reverse proxy for Docker services
  dockergen:
    build: ./dockergen
    container_name: nginx-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - proxy-certs:/etc/nginx/certs:ro
      - proxy-conf.d:/etc/nginx/conf.d
      - proxy-vhost.d:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  # Automatic Letsencrypt SSL certificate creation
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt-companion
    restart: always
    volumes:
      - proxy-certs:/etc/nginx/certs:rw
      - proxy-conf.d:/etc/nginx/conf.d
      - proxy-vhost.d:/etc/nginx/vhost.d
      - proxy-dhparam:/etc/nginx/dhparam:ro
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    networks:
      - proxy-tier
    depends_on:
      - proxy
      - dockergen

volumes:
  proxy-certs:
  proxy-conf.d:
  proxy-vhost.d:
  proxy-dhparam:
  proxy-html:

networks:
  proxy-tier:
    ipam:
      driver: default
      config:
      -
        subnet: <SPECIFY-SUBNET-HERE>
